server:
  port: 8001
spring:
  application:
    name: resIndex  #resIndex是此服务注册到nacos的服务名
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
  thymeleaf:
    mode: HTML
    cache: false #关闭缓存，不然修改会立即生效，在生产环境可配置为true
#关闭thymeleaf缓存
#  thymeleaf:
#    mode: HTML
#    cache: false
#  # i18n 国际化
#  messages:
#    basename: i18n.messages # 设置国际化文件的存储位置  默认是 messages

logging:
  level:
    root: info
    org.springframeworkb: debug
    com.apache: error
    com.yc.api: debug
  file:
    #name: mylog.log
    path: logs/

management:
  endpoints:
    web:  #以web端点
      exposure:
        include: "*"
      base-path: /resindex/actuator